#!/usr/bin/env python3

from urllib import request
import argparse

from bs4 import BeautifulSoup
from prettytable import PrettyTable


# This ugliness lets you find substrings {https://stackoverflow.com/questions/27859064/python-argparse-choices-of-string-list-accept-unique-partial-list-element#27859662}
choices = ['Premier_League', 'EFL_Championship', 'EFL_League_One', 'EFL_League_Two']
def substring(s):
    options = [c for c in choices if s in c.lower()]
    if len(options) == 1:
        return options[0]
    return s
parser = argparse.ArgumentParser(description='Fetch EFL league tables')
parser.add_argument('league', choices=choices, type=substring)
args = parser.parse_args()


html = request.urlopen("https://en.wikipedia.org/wiki/Template:2019-20_{}_table".format(args.league))
soup = BeautifulSoup(html, features="html5lib")
table = soup.find("table", {"class" : "wikitable"})
pretty = PrettyTable()
pretty.title = 'Current EFL Championship League Table'
pretty.field_names = ['Pos', 'Team', 'Pld', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts']
pos=0
for row in table.find_all('tr'):
    col_html = row.find_all('td')
    col = map(lambda i: i.get_text(), col_html)
    if len(col_html) > 1:
        pos = pos + 1
        pretty.add_row([pos]+list(col)[:9])

print(pretty)
